config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'
  resources :people

end

app/models/banner.rb
class Banner < ActiveRecord::Base

end

app/models/city.rb
class City < ActiveRecord::Base

end

app/models/house.rb
class House < ActiveRecord::Base
  has_many :people

end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :house

  validates :name, presence: true
  validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!

  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_parameters)
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def show
    @person = Person.find(params[:id])
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    @person.update_attributes!(person_parameters)

    redirect_to people_path
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    redirect_to people_path
  end

  private
  def person_parameters
    params.require(:person).permit(:name, :description)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameOfThrones</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/people/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing People</h1>
<table>
  <tr>
    <th>Person</th>
    <th>Description</th>
  </tr>

===================================================<br>

  <% @people.each do |person| %>
    <tr>
      <td><%= person.name %></td>
      <td><%= person.description %></td>
      <td><%= link_to 'Show', person_path(person) %></td>
      <td><%= link_to 'Edit', edit_person_path(person) %></td>
      <td><%= link_to 'Delete', person_path(person), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Back to Index', root_path %>

app/views/people/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p>
  <strong>Name: </strong>
  <%= @person.name %>
</p>
<p>
  <strong>Description: </strong>
  <%= @person.description %>
</p>

<%= link_to 'View List of People', people_path %><br>
<br>
<%= link_to 'Back to Index', root_path %>

app/views/welcome/index.html.erb
<h2>Welcome</h2>

<%= link_to 'Add a Person', new_person_path %><br>
<br>
<%= link_to 'View List of People', people_path %>